name: CI

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.4]
        dependency-version: [prefer-lowest, prefer-stable]

    name: CI - PHP ${{ matrix.php }} (${{ matrix.dependency-version }})

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, zip
        tools: composer:v2
        coverage: pcov

    - name: Install Composer dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

    - name: Type Checks
      run: vendor/bin/phpstan analyse

    - name: Unit Tests
      run: vendor/bin/pest --colors=always --coverage-text --coverage-clover=coverage.clover

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
